version: '3.8'

services:
  # Serveur MariaDB
  db:
    image: mariadb:10.5
    container_name: mariadb_db
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_password
      MYSQL_ROOT_PASSWORD: root_password # Optionnel
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - wp-network

  # Serveur web Apache (WordPress)
  wordpress:
    image: wordpress:php8.0-apache
    container_name: wordpress_app
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306  # Changez le port pour MariaDB
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: wp_password
    volumes:
      - ./wp-data:/var/www/html
    ports:
      - "8080:80"
    networks:
      - wp-network
    depends_on:
      - db

volumes:
  db-data:
    driver: local

networks:
  wp-network:
    driver: bridge
